#!/bin/csh 

set ORIG_SRC = $argv[1]
set dest = $argv[2]
set NODOMAIN = $dest/../nodomaincore
set PRE_DEST = $dest/../precore
set REPKG_DEST = $dest

./core-rpkg.pl -m -d $NODOMAIN $ORIG_SRC undomain.pkg

./core-rpkg.pl -m -d $PRE_DEST $NODOMAIN cougaar9core.pkg

./core-rpkg.pl -m -d $REPKG_DEST $PRE_DEST postprocess.pkg

./core-rpkg.pl -m -d $REPKG_DEST/org/cougaar/core/agent $REPKG_DEST/org/cougaar/core/agent agent.pkg

./core-rpkg.pl -m -d $REPKG_DEST/org/cougaar/core/service $REPKG_DEST/org/cougaar/core/service service.pkg

./core-rpkg.pl -m -d $REPKG_DEST/org/cougaar/core/agent/service/alarm $REPKG_DEST/org/cougaar/core/agent/service/alarm alarm.pkg

./core-rpkg.pl -m -d $REPKG_DEST/org/cougaar/core/agent/service/democontrol $REPKG_DEST/org/cougaar/core/agent/service/democontrol democontrol.pkg

./core-rpkg.pl -m -d $REPKG_DEST/org/cougaar/core/agent/service/scheduler $REPKG_DEST/org/cougaar/core/agent/service/scheduler scheduler.pkg

./core-rpkg.pl -m -d $REPKG_DEST/org/cougaar/core/agent/service/sharedthreading $REPKG_DEST/org/cougaar/core/agent/service/sharedthreading sharedthreading.pkg

./core-rpkg.pl -m -d $REPKG_DEST/org/cougaar/core/agent/service/uid $REPKG_DEST/org/cougaar/core/agent/service/uid uid.pkg

./core-rpkg.pl -m -d $REPKG_DEST/org/cougaar/core/blackboard $REPKG_DEST/org/cougaar/core/blackboard blackboard.pkg

./core-rpkg.pl -m -d $REPKG_DEST/org/cougaar/core/mts $REPKG_DEST/org/cougaar/core/mts mts.pkg

./core-rpkg.pl -m -d $REPKG_DEST/org/cougaar/core/util $REPKG_DEST/org/cougaar/core/util util.pkg

./core-rpkg.pl -m -d $REPKG_DEST/org/cougaar/core/node $REPKG_DEST/org/cougaar/core/node node.pkg

./core-rpkg.pl -m -d $REPKG_DEST/org/cougaar/core/agent/service/registry $REPKG_DEST/org/cougaar/core/agent/service/registry registry.pkg

./core-rpkg.pl -m -d $REPKG_DEST/org/cougaar/core/agent/service/domain $REPKG_DEST/org/cougaar/core/agent/service/domain domain.pkg

./core-rpkg.pl -m -d $REPKG_DEST/org/cougaar/core/domain $REPKG_DEST/org/cougaar/core/domain occdomain.pkg

./core-rpkg.pl -m -d $REPKG_DEST/org/cougaar/planning/plugin $REPKG_DEST/org/cougaar/planning/plugin coreplugin.pkg

# get rid of any left over references to cluster and society
./core-rpkg.pl -m -d $REPKG_DEST $REPKG_DEST unclustersociety.pkg

# add extra imports of each other for packages that got split into 2
# ie cluster.* went to blackboard and agent
./extraimports.pl $REPKG_DEST/org/cougaar/core/agent

./extraimports.pl $REPKG_DEST/org/cougaar/core/blackboard

./extraimports.pl $REPKG_DEST/org/cougaar/core/mts

./extraimports.pl $REPKG_DEST/org/cougaar/core/node

# allow service impls to import their service api's and agent*
./serviceimpl.pl $REPKG_DEST/org/cougaar/core/agent/service
./myserviceapi.pl $REPKG_DEST/org/cougaar/core/logging
./myserviceapi.pl $REPKG_DEST/org/cougaar/core/mts
./myserviceapi.pl $REPKG_DEST/org/cougaar/core/naming

# special case add occ.domain.* to these service impls
./domainimpl.pl $REPKG_DEST/org/cougaar/core/agent/service/domain
./domainimpl.pl $REPKG_DEST/org/cougaar/core/agent/service/registry

# special case add occ.agent.service.alarm.* to these service impls
./democontrolimpl.pl $REPKG_DEST/org/cougaar/core/agent/service/democontrol

# special blackboard adds to lps
./lps.pl $REPKG_DEST/org/cougaar/planning/ldm/lps

# more special cases
./specialagent.pl $REPKG_DEST/org/cougaar/core/agent
./specialservice.pl $REPKG_DEST/org/cougaar/core/service
./specialplan.pl $REPKG_DEST/org/cougaar/planning/ldm/plan
./specialasset.pl $REPKG_DEST/org/cougaar/planning/ldm/asset
./specialplugin.pl $REPKG_DEST/org/cougaar/core/plugin
./specialblackboard.pl $REPKG_DEST/org/cougaar/core/blackboard
./specialnode.pl $REPKG_DEST/org/cougaar/core/node
./specialcoreutil.pl $REPKG_DEST/org/cougaar/core/util
./specialpluginutil.pl $REPKG_DEST/org/cougaar/core/plugin/util
