<?xml version="1.0"?>

<!--
<copyright>
 Copyright 2001-2004 BBNT Solutions, LLC
 under sponsorship of the Defense Advanced Research Projects Agency (DARPA).

 This program is free software; you can redistribute it and/or modify
 it under the terms of the Cougaar Open Source License as published by
 DARPA on the Cougaar Open Source Website (www.cougaar.org).

 THE COUGAAR SOFTWARE AND ANY DERIVATIVE SUPPLIED BY LICENSOR IS
 PROVIDED 'AS IS' WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS OR
 IMPLIED, INCLUDING (BUT NOT LIMITED TO) ALL IMPLIED WARRANTIES OF
 MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE, AND WITHOUT
 ANY WARRANTIES AS TO NON-INFRINGEMENT.  IN NO EVENT SHALL COPYRIGHT
 HOLDER BE LIABLE FOR ANY DIRECT, SPECIAL, INDIRECT OR CONSEQUENTIAL
 DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE OF DATA OR PROFITS,
 TORTIOUS CONDUCT, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
 PERFORMANCE OF THE COUGAAR SOFTWARE.
</copyright>
-->

<!--
Default XSL template for loading standard agents and nodes.

This file is optional and is not used by default.  The default node
XML parser can generate this file at runtime by running the
"make_society.xsl" template on the full XML file.  If only standard
agents and nodes are defined (no "template=" attributes) then the
generated XSL will be equivalent to this file.

The runtime overhead of the "make_society.xsl" is relatively small,
so most developers should use that approach.  The advantage of this
template is that it may be easier to understand and modify.

This file was generated by "make_society.xsl" on a standard config:
  java\
    org.apache.xalan.xslt.Process\
    -in $COUGAAR_INSTALL_PATH/csmart/scripts/mySociety.xml \
    -xsl make_society.xsl

To use this file, either:
  a) add an xml-spreadsheet command to the top of your XML file:
       <xml-stylesheet type="text/xml" href="society.xsl"?>
or
  b) set the following system property:
       -Dorg.cougaar.society.xsl.default.file=society.xsl

The fully expanded configuration can be generated by:
  java\
    org.apache.xalan.xslt.Process\
    -in $COUGAAR_INSTALL_PATH/csmart/scripts/mySociety.xml \
    -xsl society.xsl
-->
<xsl:stylesheet
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  version="1.0">

  <!-- use "include" to check for conflicts -->
  <xsl:include href="SimpleAgent.xsl"/>
  <xsl:include href="NodeAgent.xsl"/>

  <!-- check for unknown templates -->
  <xsl:template match="agent|node">
    <xsl:message>
      <xsl:text>Unknown template "</xsl:text>
      <xsl:value-of select="@template"/>
      <xsl:text>" specified by </xsl:text>
      <xsl:value-of select="name()"/>
      <xsl:text> "</xsl:text>
      <xsl:value-of select="@name"/>
      <xsl:text>", need to run "make_society.xsl" again?</xsl:text>
    </xsl:message>
    <xsl:apply-templates/>
  </xsl:template>
</xsl:stylesheet>
