#!/bin/sh
COUGAAR3RDPARTY=${QUOEXAMPLES}/cougaar/3rdparty
export COUGAAR3RDPARTY

newcore=${COUGAAR_SRC_PATH}/core/src/org/cougaar/core/society/newcore.jar

# Include event-channel jar on CLASSPATH now

# Because of the way cougaar messes with the class loader, the
# jacorb.jar has to go on classpath (via COUGAAR_DEV_PATH), not on
# bootclasspath

COUGAAR_DEV_PATH=${newcore}:${QUOEXAMPLES}/cougaar/configs/performance_config/perf-society.jar:${QUOEXAMPLES}/cougaar/quoCougaar.jar:${JACORB_DIR}/lib/jacorb.jar
###:${QUOJAR}/QuoInstr.jar:${QUOJAR}/QuoKernel.jar:${QUOJAR}/UnixUtils.jar
export COUGAAR_DEV_PATH

#cougaar_quo_log=`hostname`-$1-`date +%y%m%d%H%M%S`.log

# Force alp to run JacORB CORBA (channel require CORBA) 

#JACORB_ARGS="-Xbootclasspath:${JACORB_DIR}/lib/jacorb.jar:${JAVA_HOME}/jre/lib/rt.jar -Dorg.omg.CORBA.ORBClass=org.jacorb.orb.ORB -Dorg.omg.CORBA.ORBSingletonClass=org.jacorb.orb.ORBSingleton "

JACORB_ARGS=" -Dorg.omg.CORBA.ORBClass=org.jacorb.orb.ORB -Dorg.omg.CORBA.ORBSingletonClass=org.jacorb.orb.ORBSingleton "

. ${QUOSHARE}/dirm/remos/bin/remosENV

COUGAAR_JAVA_ARGS="-DCOLLECTOR=$COLLECTOR -DDOMAIN=bbn.com -Dorg.cougaar.properties.url=file:${QUOEXAMPLES}/cougaar/cougaar.props -Dorg.cougaar.lib.quo.logfile=${cougaar_quo_log} -Dorg.cougaar.useBootstrapper=true  $JACORB_ARGS"
export COUGAAR_JAVA_ARGS

LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${QUOLIB}
export LD_LIBRARY_PATH


#exec ${COUGAAR_INSTALL_PATH}/bin/Node $*
exec ${COUGAAR_SRC_PATH}/core/bin/Node $*

