// Skeleton class generated by rmic, do not edit.
// Contents subject to change without notice.

package org.cougaar.tools.server;

public final class RemoteOutputStreamImpl_Skel
    implements java.rmi.server.Skeleton
{
    private static final java.rmi.server.Operation[] operations = {
	new java.rmi.server.Operation("void close()"),
	new java.rmi.server.Operation("void write(org.cougaar.tools.server.RemoteOutputStream.ByteArray)")
    };
    
    private static final long interfaceHash = -3853296237394704472L;
    
    public java.rmi.server.Operation[] getOperations() {
	return (java.rmi.server.Operation[]) operations.clone();
    }
    
    public void dispatch(java.rmi.Remote obj, java.rmi.server.RemoteCall call, int opnum, long hash)
	throws java.lang.Exception
    {
	if (opnum < 0) {
	    if (hash == -4742752445160157748L) {
		opnum = 0;
	    } else if (hash == -7503023837992041611L) {
		opnum = 1;
	    } else {
		throw new java.rmi.UnmarshalException("invalid method hash");
	    }
	} else {
	    if (hash != interfaceHash)
		throw new java.rmi.server.SkeletonMismatchException("interface hash mismatch");
	}
	
	org.cougaar.tools.server.RemoteOutputStreamImpl server = (org.cougaar.tools.server.RemoteOutputStreamImpl) obj;
	switch (opnum) {
	case 0: // close()
	{
	    call.releaseInputStream();
	    server.close();
	    try {
		call.getResultStream(true);
	    } catch (java.io.IOException e) {
		throw new java.rmi.MarshalException("error marshalling return", e);
	    }
	    break;
	}
	    
	case 1: // write(RemoteOutputStream.ByteArray)
	{
	    org.cougaar.tools.server.RemoteOutputStream.ByteArray $param_RemoteOutputStream$ByteArray_1;
	    try {
		java.io.ObjectInput in = call.getInputStream();
		$param_RemoteOutputStream$ByteArray_1 = (org.cougaar.tools.server.RemoteOutputStream.ByteArray) in.readObject();
	    } catch (java.io.IOException e) {
		throw new java.rmi.UnmarshalException("error unmarshalling arguments", e);
	    } catch (java.lang.ClassNotFoundException e) {
		throw new java.rmi.UnmarshalException("error unmarshalling arguments", e);
	    } finally {
		call.releaseInputStream();
	    }
	    server.write($param_RemoteOutputStream$ByteArray_1);
	    try {
		call.getResultStream(true);
	    } catch (java.io.IOException e) {
		throw new java.rmi.MarshalException("error marshalling return", e);
	    }
	    break;
	}
	    
	default:
	    throw new java.rmi.UnmarshalException("invalid method number");
	}
    }
}
