// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package org.cougaar.tools.server;

public final class RemoteNodeServerImpl_Stub
    extends java.rmi.server.RemoteStub
    implements org.cougaar.tools.server.RemoteNodeServer, java.rmi.Remote
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_createNode_0;
    private static java.lang.reflect.Method $method_destroyNode_1;
    private static java.lang.reflect.Method $method_getNodeCount_2;
    private static java.lang.reflect.Method $method_getNodes_3;
    private static java.lang.reflect.Method $method_reset_4;
    
    static {
	try {
	    $method_createNode_0 = org.cougaar.tools.server.RemoteNodeServer.class.getMethod("createNode", new java.lang.Class[] {java.lang.String.class, java.util.Properties.class, java.lang.String[].class, org.cougaar.tools.server.RemoteOutputStream.class, org.cougaar.tools.server.RemoteOutputStream.class});
	    $method_destroyNode_1 = org.cougaar.tools.server.RemoteNodeServer.class.getMethod("destroyNode", new java.lang.Class[] {java.lang.String.class});
	    $method_getNodeCount_2 = org.cougaar.tools.server.RemoteNodeServer.class.getMethod("getNodeCount", new java.lang.Class[] {});
	    $method_getNodes_3 = org.cougaar.tools.server.RemoteNodeServer.class.getMethod("getNodes", new java.lang.Class[] {});
	    $method_reset_4 = org.cougaar.tools.server.RemoteNodeServer.class.getMethod("reset", new java.lang.Class[] {});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public RemoteNodeServerImpl_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of createNode(String, Properties, String[], RemoteOutputStream, RemoteOutputStream)
    public org.cougaar.tools.server.RemoteProcess createNode(java.lang.String $param_String_1, java.util.Properties $param_Properties_2, java.lang.String[] $param_arrayOf_String_3, org.cougaar.tools.server.RemoteOutputStream $param_RemoteOutputStream_4, org.cougaar.tools.server.RemoteOutputStream $param_RemoteOutputStream_5)
	throws java.io.IOException, java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_createNode_0, new java.lang.Object[] {$param_String_1, $param_Properties_2, $param_arrayOf_String_3, $param_RemoteOutputStream_4, $param_RemoteOutputStream_5}, 5757402735857331319L);
	    return ((org.cougaar.tools.server.RemoteProcess) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.io.IOException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of destroyNode(String)
    public boolean destroyNode(java.lang.String $param_String_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_destroyNode_1, new java.lang.Object[] {$param_String_1}, 7159991675886862877L);
	    return ((java.lang.Boolean) $result).booleanValue();
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getNodeCount()
    public int getNodeCount()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getNodeCount_2, null, -237585700862737706L);
	    return ((java.lang.Integer) $result).intValue();
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getNodes()
    public java.util.Collection getNodes()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getNodes_3, null, 5013611610657350701L);
	    return ((java.util.Collection) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of reset()
    public void reset()
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_reset_4, null, 7419395615006395270L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
